### ISSUE TITLE
Images are not round

### ISSUE THREAD

**Issue by Senko-Dev** [h-projects/h-projects.github.io#10]
```css
img {
	padding: 10px;
	border-radius: var(--radius);
}
```

This code is located in `/assets/css/topLeve/userAgentOverride.css`. This code is supposed to round the images, yet the images are not rounded.
